package com.myspace.test_general_data;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExtInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "标识")
	private String flag;
	@org.kie.api.definition.type.Label(value = "描述")
	private String desc;

	public ExtInfo() {
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public ExtInfo(String flag, String desc) {
		this.flag = flag;
		this.desc = desc;
	}

}
