package com.myspace.test_general_data;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FIleOpLog implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("唯一ID")
	private String gid;
	@org.kie.api.definition.type.Label("时间戳")
	private Long logtime;
	@org.kie.api.definition.type.Label("行为结果")
	private String a_result;
	@org.kie.api.definition.type.Label("行为描述")
	private String a_desc;
	@org.kie.api.definition.type.Label("操作类型")
	private String op_type;

	@org.kie.api.definition.type.Label(value = "格式化后的日期(yyyy-MM-dd HH:mm:ss)")
	private String logtime_format;

	@org.kie.api.definition.type.Label(value = "标识")
	private String flag;

	@org.kie.api.definition.type.Label(value = "source_app")
	private String source_app;

	@org.kie.api.definition.type.Label(value = "sub_type")
	private String sub_type;

	@org.kie.api.definition.type.Label(value = "sub_id")
	private String sub_id;

	@org.kie.api.definition.type.Label(value = "obj_type")
	private String obj_type;

	@org.kie.api.definition.type.Label(value = "obj_id")
	private String obj_id;

	@org.kie.api.definition.type.Label(value = "pc_id")
	private String pc_id;

	@org.kie.api.definition.type.Label(value = "pc_ip")
	private String pc_ip;

	@org.kie.api.definition.type.Label(value = "op_procn")
	private String op_procn;

	@org.kie.api.definition.type.Label(value = "sec_level")
	private String sec_level;

	@org.kie.api.definition.type.Label(value = "a_type")
	private String a_type;

	@org.kie.api.definition.type.Label(value = "src_dev_t")
	private String src_dev_t;

	@org.kie.api.definition.type.Label(value = "src_dev_id")
	private String src_dev_id;

	@org.kie.api.definition.type.Label(value = "dst_dev_t")
	private String dst_dev_t;

	@org.kie.api.definition.type.Label(value = "dst_dev_id")
	private String dst_dev_id;

	@org.kie.api.definition.type.Label(value = "小时")
	private Integer logtime_hour;

	public FIleOpLog() {
	}

	public String getGid() {
		return this.gid;
	}

	public void setGid(String gid) {
		this.gid = gid;
	}

	public Long getLogtime() {
		return this.logtime;
	}

	public void setLogtime(Long logtime) {
		this.logtime = logtime;
	}

	public String getA_result() {
		return this.a_result;
	}

	public void setA_result(String a_result) {
		this.a_result = a_result;
	}

	public String getA_desc() {
		return this.a_desc;
	}

	public void setA_desc(String a_desc) {
		this.a_desc = a_desc;
	}

	public String getOp_type() {
		return this.op_type;
	}

	public void setOp_type(String op_type) {
		this.op_type = op_type;
	}

	public String getLogtime_format() {
		return this.logtime_format;
	}

	public void setLogtime_format(String logtime_format) {
		this.logtime_format = logtime_format;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public String getSource_app() {
		return this.source_app;
	}

	public void setSource_app(String source_app) {
		this.source_app = source_app;
	}

	public String getSub_type() {
		return this.sub_type;
	}

	public void setSub_type(String sub_type) {
		this.sub_type = sub_type;
	}

	public String getSub_id() {
		return this.sub_id;
	}

	public void setSub_id(String sub_id) {
		this.sub_id = sub_id;
	}

	public String getObj_type() {
		return this.obj_type;
	}

	public void setObj_type(String obj_type) {
		this.obj_type = obj_type;
	}

	public String getObj_id() {
		return this.obj_id;
	}

	public void setObj_id(String obj_id) {
		this.obj_id = obj_id;
	}

	public String getPc_id() {
		return this.pc_id;
	}

	public void setPc_id(String pc_id) {
		this.pc_id = pc_id;
	}

	public String getPc_ip() {
		return this.pc_ip;
	}

	public void setPc_ip(String pc_ip) {
		this.pc_ip = pc_ip;
	}

	public String getOp_procn() {
		return this.op_procn;
	}

	public void setOp_procn(String op_procn) {
		this.op_procn = op_procn;
	}

	public String getSec_level() {
		return this.sec_level;
	}

	public void setSec_level(String sec_level) {
		this.sec_level = sec_level;
	}

	public String getA_type() {
		return this.a_type;
	}

	public void setA_type(String a_type) {
		this.a_type = a_type;
	}

	public String getSrc_dev_t() {
		return this.src_dev_t;
	}

	public void setSrc_dev_t(String src_dev_t) {
		this.src_dev_t = src_dev_t;
	}

	public String getSrc_dev_id() {
		return this.src_dev_id;
	}

	public void setSrc_dev_id(String src_dev_id) {
		this.src_dev_id = src_dev_id;
	}

	public String getDst_dev_t() {
		return this.dst_dev_t;
	}

	public void setDst_dev_t(String dst_dev_t) {
		this.dst_dev_t = dst_dev_t;
	}

	public String getDst_dev_id() {
		return this.dst_dev_id;
	}

	public void setDst_dev_id(String dst_dev_id) {
		this.dst_dev_id = dst_dev_id;
	}

	public Integer getLogtime_hour() {
		return this.logtime_hour;
	}

	public void setLogtime_hour(Integer logtime_hour) {
		this.logtime_hour = logtime_hour;
	}

	public FIleOpLog(String gid, Long logtime,
                     String a_result, String a_desc,
                     String op_type, String logtime_format,
                     String flag, String source_app,
                     String sub_type, String sub_id,
                     String obj_type, String obj_id,
                     String pc_id, String pc_ip,
                     String op_procn, String sec_level,
                     String a_type, String src_dev_t,
                     String src_dev_id, String dst_dev_t,
                     String dst_dev_id, Integer logtime_hour) {
		this.gid = gid;
		this.logtime = logtime;
		this.a_result = a_result;
		this.a_desc = a_desc;
		this.op_type = op_type;
		this.logtime_format = logtime_format;
		this.flag = flag;
		this.source_app = source_app;
		this.sub_type = sub_type;
		this.sub_id = sub_id;
		this.obj_type = obj_type;
		this.obj_id = obj_id;
		this.pc_id = pc_id;
		this.pc_ip = pc_ip;
		this.op_procn = op_procn;
		this.sec_level = sec_level;
		this.a_type = a_type;
		this.src_dev_t = src_dev_t;
		this.src_dev_id = src_dev_id;
		this.dst_dev_t = dst_dev_t;
		this.dst_dev_id = dst_dev_id;
		this.logtime_hour = logtime_hour;
	}

}
